# Generated by Django 4.2.16 on 2026-05-26 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Technology', 'Technology'), ('History', 'History'), ('Biography', 'Biography'), ('Philosophy', 'Philosophy'), ('Self-Help', 'Self-Help'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Children', 'Children'), ('Education', 'Education'), ('Art', 'Art')], max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
    ]
